### ISSUE TITLE
Price and tax histories are unable to be populated

### ISSUE THREAD

**Issue by KaroAntonio** [hahnicity/scrapezillow#4]
Attempting to run this via command prompt or in a python script via url or zpid methods all yield a:

UnboundLocalError: local variable 'full_url' referenced before assignment

The full readout:

 scrapezillow --url http://www.zillow.com/homedetails/4963-W-Onyx-Ave-Glendale-AZ-85302/7728923_zpid/
Traceback (most recent call last):
  File "/usr/local/bin/scrapezillow", line 9, in <module>
    load_entry_point('scrapezillow==0.3', 'console_scripts', 'scrapezillow')()
  File "/Library/Python/2.7/site-packages/scrapezillow/main.py", line 14, in main
    pprint(scrape_url(**args.__dict__))
  File "/Library/Python/2.7/site-packages/scrapezillow/scraper.py", line 183, in scrape_url
    ajax_url = _get_ajax_url(soup,"z-hdp-price-history")
  File "/Library/Python/2.7/site-packages/scrapezillow/scraper.py", line 128, in _get_ajax_url
    return full_url
UnboundLocalError: local variable 'full_url' referenced before assignment

**Comment by hahnicity** [comment]
Probably a schema change. Let me see what I can do.

**Comment by hahnicity** [comment]
OK i fixed the parser on master but it won't be able to grab price or tax histories. If you want to use it you will need to build the code from the git repo instead of installing from pip. I need to allocate some time to fix the price and tax history population before I push to pip again. 

I'm going to keep this bug open until I fix those two properties.

**Comment by KaroAntonio** [comment]
Alright, well thanks for looking into it!

**Comment by hahnicity** [comment]
Thanks for your bug report. I just fixed this issue. It will be on pip in a minute
